#./build/examples/openpose/openpose.bin --write_video /openpose/project/data/andrea_hand.avi --video /openpose/project/data/andrea_clip.mp4 --write_json /openpose/project/data/keypoints/andrea_hand/ --face --hand --hand_scale_number 6 --hand_scale_range 0.4

version: '2.3'

services:

  openpose:
    image: openpose
    container_name: openpose
    working_dir: /openpose
    build:
      context: ../
      dockerfile: docker/Dockerfile.openpose
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - ../:/openpose/project
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    command: tail /dev/null -f

  pose2avatar:
    image: pose2avatar
    container_name: pose2avatar
    working_dir: /pose2avatar
    build:
      context: ../
      dockerfile: docker/Dockerfile.pose2avatar
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - ../:/pose2avatar
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
    command: tail /dev/null -f