version: '2.3'

services:

  openpose:
    image: openpose
    container_name: openpose
    working_dir: /openpose
    build:
      context: ../
      dockerfile: docker/Dockerfile.openpose
    volumes:
      - ../:/openpose/project
    runtime: nvidia
    command: tail /dev/null -f

  pose2avatar:
    image: pose2avatar
    container_name: pose2avatar
    working_dir: /pose2avatar/src
    build:
      context: ../
      dockerfile: docker/Dockerfile.pose2avatar
    volumes:
      - ../:/pose2avatar
    runtime: nvidia
    command: tail /dev/null -f