#./build/examples/openpose/openpose.bin --video /pose2char/data/test_me.mp4 --write_video /pose2char/output/test_me_pose.avi --write_json /pose2char/data/keypoints/test_me/

version: '2.3'

services:

  pose2char:
    image: pose2char
    container_name: pose2char
    working_dir: /pose2char
    build:
      context: ../
      dockerfile: docker/Dockerfile.pose

# Setup environment variables:
    environment:
      - PYTHONPATH=/pose2char
      # Uncomment the following line to plot images on Linux
      - DISPLAY=unix$DISPLAY
      # Set a password to your Jupyter Notebook
      #- PASSWORD=testpass
      
# Setup the ports you want to expose:
    # ports:
    # Jupyter port
      #- "8888:8888"

# Setup the volumes you want to share:    
    volumes:
      - ../:/pose2char
      #Share the webcam with the container
      #- /dev/video0:/dev/video0
      # Uncomment the following line to plot images on Linux
      - /tmp/.X11-unix:/tmp/.X11-unix

# Uncomment the following line to use an NVIDIA GPU (requires nvidia-docker)
    runtime: nvidia

# By default this container stay alive without running any command 
    command: tail /dev/null -f
# If installed, you can start Jupyter Notebook every time you run the container
    #command: jupyter notebook --allow-root

  blender:
    image: blender
    container_name: blender
    working_dir: /pose2char
    build:
      context: ../
      dockerfile: docker/Dockerfile.blender

# Setup environment variables:
    environment:
      - PYTHONPATH=/pose2char
      # Uncomment the following line to plot images on Linux
      - DISPLAY=unix$DISPLAY
      # Set a password to your Jupyter Notebook
      #- PASSWORD=testpass
      
# Setup the ports you want to expose:
    # ports:
    # Jupyter port
      #- "8888:8888"

# Setup the volumes you want to share:    
    volumes:
      - ../:/pose2char
      #Share the webcam with the container
      #- /dev/video0:/dev/video0
      # Uncomment the following line to plot images on Linux
      - /tmp/.X11-unix:/tmp/.X11-unix

# Uncomment the following line to use an NVIDIA GPU (requires nvidia-docker)
    runtime: nvidia

# By default this container stay alive without running any command 
    command: tail /dev/null -f
# If installed, you can start Jupyter Notebook every time you run the container
    #command: jupyter notebook --allow-root